server:
  port: 8080
spring:
  task:
    scheduling:
      pool:
        size: 10
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10000000MB
      max-request-size: 10000000MB
  jpa:
    jdbc:
      time_zone: Asia/Phnom_Penh
      batch_size: 1000
    open-in-view: true
    show-sql: true
cloudinary: 
  url: ${CLOUDINARY_URL:cloudinary://878231315371161:_v9bFowIqhd8RQ1bw1LKtoFkmtM@dohtq6cbz}
  default-image: https://res.cloudinary.com/dohtq6cbz/image/upload/v1731050338/stock-user/test2test2.png
  # default-image: https://res.cloudinary.com/dohtq6cbz/image/upload/v1731051235/empty_mjkuxf.jpg
postgress-connection:
  #jdbc-url: jdbc:postgresql://${DB_HOST:localhost}:5432/stocker
  jdbc-url: jdbc:postgresql://${DB_HOST:ec2-3-17-133-210.us-east-2.compute.amazonaws.com}:5432/stocker
  # jdbc-url: jdbc:postgresql://${DB_HOST:ec2-3-17-133-210.us-east-2.compute.amazonaws.com}:5432/test
  driver-class-name: org.postgresql.Driver
  username: ${DB_USER:admin}
  password: ${DB_PASS:admin}
  maximum-pool-size: 10
  connection-timeout: 50000
  idle-timeout: 30000
  minimum-idle: 30000
  max-lifetime: 30000
  keep-alive: 30000
  hibernate:
    ddl-auto: none
    dialect: org.hibernate.dialect.PostgreSQLDialect
    enable_lazy_load_no_trans: false

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      # expiration: 40 # a day
      refresh-token:
        expiration: 604800000 # 7 days
cache:
  product:
    name: product-cache
    ttl: 1000000
  customer:
    name: customer-cache
    ttl: 10000
  user: 
    name: user-cache
    ttl: 10000
# logging:
#   config: classpath:log4j2.xml
rest:
  telegram:
    url: https://api.telegram.org/bot7758004942:AAHxjD_dEeRFuB-lgMSUoMzc2uBZ6Uivstg1
    monitor:
      chat-id: -4687885873
    

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic